// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           27
// Async Callback (empty):               1
// Total number of exported functions:  29

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    staking_v2_sc
    (
        init => init
        upgrade => upgrade
        routerAddress => router_address
        staked => staked
        stakedIter => staked_iter
        stakedTime => staked_time
        nbStaked => nb_staked
        nbPlayers => nb_players
        lastEpisodeClaimed => last_episode_claimed
        episodesTimestamps => episodes_timestamps
        episodesRewards => episodes_rewards
        currentEpisode => current_episode
        claimedPerEpisode => claimed_per_episode
        depositEcity => deposit_ecity
        addEcity => add_ecity
        stake => stake
        unstakeSingle => unstake_single
        unstake => unstake
        claimEcity => claim_ecity
        claim => claim
        fakeClaim => fake_claim
        claimUnclaimable => claim_unclaimable
        setEcityTokenid => set_ecity_tokenid
        setGnsTokenid => set_gns_tokenid
        setExpTokenid => set_exp_tokenid
        setCtznTokenid => set_ctzn_tokenid
        setRouterAddress => set_router_address
        addToCollections => add_to_collections
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
